"""5th migration

Revision ID: b8034efbcb6c
Revises: 3cf51f5b1199
Create Date: 2023-11-21 13:28:28.050672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8034efbcb6c'
down_revision = '3cf51f5b1199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimodel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimodel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
