"""4th migration

Revision ID: 3cf51f5b1199
Revises: 
Create Date: 2023-11-21 12:35:52.883094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf51f5b1199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bimodel',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('business_scale', sa.String(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('no_of_users', sa.String(), nullable=True),
    sa.Column('deployment', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('mobile_apps', sa.String(), nullable=True),
    sa.Column('pricing', sa.String(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bimodel')
    # ### end Alembic commands ###
