# Generated by Django 4.1.13 on 2023-12-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiModelPostgres',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('business_scale', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('no_of_users', models.CharField(max_length=100)),
                ('deployment', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('mobile_apps', models.CharField(max_length=100)),
                ('pricing', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=1500)),
            ],
        ),
        migrations.RenameModel(
            old_name='BiModel',
            new_name='BiModelMongo',
        ),
    ]
